apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 1.9.5
  name: kube-state-metrics
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - name: http-metrics
    port: 8080
    targetPort: http-metrics
    nodePort: 30005
  - name: telemetry
    port: 8081
    targetPort: telemetry
    nodePort: 30006
  selector:
    app.kubernetes.io/name: kube-state-metrics
