apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: openfaas
spec:
  selector:
    app: node-exporter
  type: NodePort
  ports:
    - port: 9100
      targetPort: 9100
      nodePort: 30001