apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  name: cadvisor
  namespace: cadvisor
  labels:
    name: cadvisor
spec:
  type: NodePort
  ports:
  - port: 9110
    protocol: TCP
    targetPort: 8080
    nodePort: 31120
  selector:
    name: cadvisor