container_image: sentimentanalysis
database:
    host: 138.246.234.122
    name: prometheus
    password: admin
    port: 8086
    username: admin
master_ip: 54.160.12.136
model_functions:
    instance1:
        clusterconfig:
            image: '"ami-055df5de4f42cf331"'
            instance: '"t2.large"'
            master_nodes: '["master"]'
            region: '"us-east-1"'
            worker_nodes: '["worker1", "worker2"]'
        function:
            image: null
            name: sentimentanalysis
            store: true
        function_deployment:
            deployment: f_deployment.py
            function_params: ''
        k8: true
        post_test:
            data_extraction: true
            modeling: true
            plot: true
        pre_test:
            cluster_deployment: false
            function_deployment: false
        test:
            function_params: '"Personally I like functions to do one thing and only
                one thing well, it makes them more readable."'
            k6:
                customized:
                    stage: 20
            start: 0
            test_run: k6_run_script.py
    instance2:
        clusterconfig:
            image: '"ami-055df5de4f42cf331"'
            instance: '"t2.xlarge"'
            master_nodes: '["master"]'
            region: '"us-east-1"'
            worker_nodes: '["worker1", "worker2"]'
        function:
            image: null
            name: sentimentanalysis
            store: true
        function_deployment:
            deployment: f_deployment.py
            function_params: ''
        k8: true
        post_test:
            data_extraction: false
            modeling: false
            plot: false
        pre_test:
            cluster_deployment: false
            function_deployment: false
        test:
            function_params: '"Personally I like functions to do one thing and only
                one thing well, it makes them more readable."'
            k6:
                customized:
                    stage: 120
            start: 4
            test_run: k6_run_script.py
    instance3:
        clusterconfig:
            image: '"ami-055df5de4f42cf331"'
            instance: '"t2.micro"'
            master_nodes: '["master"]'
            region: '"us-east-1"'
            worker_nodes: '["worker1", "worker2"]'
        function:
            image: null
            name: sentimentanalysis
            store: true
        function_deployment:
            deployment: f_deployment.py
            function_params: ''
        k8: false
        post_test:
            data_extraction: false
            modeling: false
            plot: false
        pre_test:
            cluster_deployment: false
            function_deployment: false
        test:
            function_params: '"Personally I like functions to do one thing and only
                one thing well, it makes them more readable."'
            k6:
                customized:
                    stage: 5
            start: 4
            test_run: k6_run_script.py
    instance4:
        clusterconfig:
            image: '"ami-055df5de4f42cf331"'
            instance: '"t2.micro"'
            master_nodes: '["master"]'
            region: '"us-east-1"'
            worker_nodes: '["worker1", "worker2"]'
        function:
            image: theaxer/classify:latest
            name: classify
            store: false
        k8: false
        post_test:
            data_extraction: false
            modeling: false
            plot: false
        pre_test:
            cluster_deployment: false
            function_deployment: false
        test:
            function_params: '"Muthu"'
            k6:
                duration: 1m
                rps: 10
                stage:
                - 1m:10
                - 1m:10
                - 1m:20
                - 1m:20
                - 1m:30
                - 1m:40
                - 1m:50
                - 1m:60
                - 1m:70
                - 1m:80
                - 1m:90
                vus: 1
            start: 4
            test_run: k6_run_script.py
prometheus:
    api: api/v1/query_range?query=
    host: 138.246.234.122
    port: 9090
query:
    cpu:
        container_image: sentimentanalysis
        formatter: ''
        name: cpu
        percent: 50
        query: sum(rate(container_cpu_usage_seconds_total{container=~%22sentimentanalysis%22}[1m]))%2F6*100
        step: 15
    mem:
        formatter: 2147483648
        name: mem
        percent: 14.28
        query: sum(container_memory_working_set_bytes{container=~%22sentimentanalysis%22})%2F(1024*1024*1024*8)*100
        step: 15
    replica:
        formatter: ''
        name: replica
        percent: ''
        query: gateway_service_count
        step: 15
    requests:
        formatter: ''
        name: requests
        percent: 1.66
        query: sum(sum_over_time(http_reqs%5B1m%5D))
        step: 15
    responsetime:
        formatter: ''
        name: responsetime
        percent: 1.66
        query: http_req_duration%7Bstatus%3D%22200%22%7D%2F1000
        step: 15
    totalcpuUtilization:
        formatter: ''
        name: totalcpuUtilization
        percent: ''
        query: sum(instance%3Anode_cpu_utilisation%3Arate1m%7Bjob%3D%22node-exporter%22%7D)%2F3*100
        step: 15
    totalmemoryUtilization:
        formatter: ''
        name: totalmemoryUtilization
        percent: ''
        query: sum(instance%3Anode_memory_utilisation%3Aratio%7Bjob%3D%22node-exporter%22%7D)%2F3*100
        step: 15
time:
    end: '1597386533.604389'
    start: '1597385332.713849'
